# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomelabManager < Formula
  desc "Web UI and CLI to wake/sleep a Proxmox homelab"
  homepage "https://github.com/joelgrimberg/homelab-manager"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.1.0/homelab-manager_0.1.0_darwin_amd64.tar.gz"
      sha256 "e7c3778d106440a8e82fd1e07f926f544c37317af0d916cf89fdb35fe7afd8ca"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.1.0/homelab-manager_0.1.0_darwin_arm64.tar.gz"
      sha256 "f27b9e8f116eedc5ddea5ee747f88d56f10f172064842364817363c1537ba984"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.1.0/homelab-manager_0.1.0_linux_amd64.tar.gz"
      sha256 "1bffc0f0497db5651b3f37587304d9d64b2a0478aaacbbf9f66b949b92a30f90"
      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure the server URL, create ~/.config/homelab-manager/config.yaml:

        mkdir -p ~/.config/homelab-manager
        echo 'server: https://your-server-url' > ~/.config/homelab-manager/config.yaml

      Or set the HOMELAB_SERVER environment variable.
    EOS
  end

  test do
    system bin/"homelab-manager", "--help"
  end
end
