# This file was generated by GoReleaser. DO NOT EDIT.
cask "things" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_darwin_amd64.tar.gz"
      sha256 "b90fce28941a641db297f16b70222e84c0d8404355352f73a93c3732244f8d8b"
    end
    on_arm do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_darwin_arm64.tar.gz"
      sha256 "2d7096f5411e1fce7fb95610d08a8ace363e83a903c499625c1afafd7ed73e4a"
    end
  end

  on_linux do
    on_intel do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_linux_amd64.tar.gz"
      sha256 "827f39af4fead0d222bb43d74d03379cd4f615ef1b1a252b1d04eca9372a6104"
    end
    on_arm do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_linux_arm64.tar.gz"
      sha256 "a5492106158ef1d897337ccde9e57e0032b6c85941c10ff9145af948314d8301"
    end
  end

  name "things"
  desc "Keyboard-driven task manager for the terminal"
  homepage "https://things.grimbergenv.nl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "things"

  # No zap stanza required

end
