# This file was generated by GoReleaser. DO NOT EDIT.
cask "things" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_darwin_amd64.tar.gz"
      sha256 "8372bcb6957e69f79d5973e80c8d83d39a0833cb41b714bd9cc1e5d54902c484"
    end
    on_arm do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_darwin_arm64.tar.gz"
      sha256 "06db13573435b69c15622bf115c1ea5f419917cebc9f2dd2d6af591ce458ad5b"
    end
  end

  on_linux do
    on_intel do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_linux_amd64.tar.gz"
      sha256 "a5ac6f0d0f02b040604f79592821f340f37aa38ba185477d15cc1825cb3ccccc"
    end
    on_arm do
      url "https://gitlab.com/joelgrimberg/things/-/releases/v#{version}/downloads/things_#{version}_linux_arm64.tar.gz"
      sha256 "a1f1378296d982cf3f8742c4a2076461adfbab31ea090c1af8a4a3b970458ea7"
    end
  end

  name "things"
  desc "Keyboard-driven task manager for the terminal"
  homepage "https://things.grimbergenv.nl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "things"

  # No zap stanza required

end
