# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomelabManager < Formula
  desc "Web UI and CLI to wake/sleep a Proxmox homelab"
  homepage "https://github.com/joelgrimberg/homelab-manager"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.5.2/homelab-manager_0.5.2_darwin_amd64.tar.gz"
      sha256 "9e8d59eed51dd339548fbcdfdd199dbe63ea55a39d64443b05663c98f34d2cca"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.5.2/homelab-manager_0.5.2_darwin_arm64.tar.gz"
      sha256 "410f851ff6f7f51b4048f633adeac045e0b4c98e1734805674a7870919ae631e"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.5.2/homelab-manager_0.5.2_linux_amd64.tar.gz"
      sha256 "f0992a9c2bbeda33c9a62896822f07c1fca8f3ddbb5f3ebe7cdf8960aec6308c"
      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure the server URL, create ~/.config/homelab-manager/config.yaml:

        mkdir -p ~/.config/homelab-manager
        echo 'server: https://your-server-url' > ~/.config/homelab-manager/config.yaml

      Or set the HOMELAB_SERVER environment variable.
    EOS
  end

  test do
    system bin/"homelab-manager", "--help"
  end
end
