# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomelabManager < Formula
  desc "Web UI and CLI to wake/sleep a Proxmox homelab"
  homepage "https://github.com/joelgrimberg/homelab-manager"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.5.1/homelab-manager_0.5.1_darwin_amd64.tar.gz"
      sha256 "69860035bc60e05c59b512552403836ec52f27b309b76e8df8d62a76bb32ad3f"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.5.1/homelab-manager_0.5.1_darwin_arm64.tar.gz"
      sha256 "0bce444507b18a985163380b4c4132d9ea0b3dba7fdf1b9ecdfd78b5e20cbbd3"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.5.1/homelab-manager_0.5.1_linux_amd64.tar.gz"
      sha256 "b8e5e55b51a7e354120ac3578f2cc5873a8c8e3677d9bc5b0af71a7fee01040b"
      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure the server URL, create ~/.config/homelab-manager/config.yaml:

        mkdir -p ~/.config/homelab-manager
        echo 'server: https://your-server-url' > ~/.config/homelab-manager/config.yaml

      Or set the HOMELAB_SERVER environment variable.
    EOS
  end

  test do
    system bin/"homelab-manager", "--help"
  end
end
