# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HomelabManager < Formula
  desc "Web UI and CLI to wake/sleep a Proxmox homelab"
  homepage "https://github.com/joelgrimberg/homelab-manager"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.4.0/homelab-manager_0.4.0_darwin_amd64.tar.gz"
      sha256 "08036f9dd94a66baab3ef9d6c24e7adab14bfe3bde387a81c9297f532ff6e3ca"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.4.0/homelab-manager_0.4.0_darwin_arm64.tar.gz"
      sha256 "65ec17566eb9e8e2f776db513efabf58f28b188e9b22e3db478094a8f773b74f"

      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joelgrimberg/homelab-manager/releases/download/v0.4.0/homelab-manager_0.4.0_linux_amd64.tar.gz"
      sha256 "a8bde6c89444bb5de92005a64aeb6c817e27a18e4385822df1d58a626f85af92"
      define_method(:install) do
        bin.install "homelab-manager"
        (share/"fish/vendor_functions.d").install "clients/fish/homelab.fish"
        (share/"fish/vendor_functions.d").install "clients/fish/__homelab_server_url.fish"
        (share/"fish/vendor_completions.d").install "clients/fish/homelab.completions.fish" => "homelab.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To configure the server URL, create ~/.config/homelab-manager/config.yaml:

        mkdir -p ~/.config/homelab-manager
        echo 'server: https://your-server-url' > ~/.config/homelab-manager/config.yaml

      Or set the HOMELAB_SERVER environment variable.
    EOS
  end

  test do
    system bin/"homelab-manager", "--help"
  end
end
